导入模块

In [37]:
import scipy.io as sio
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import spectral

获取本地数据集

In [38]:
datafile = 'data2_train.mat'
file2 = sio.loadmat(datafile)
data2 = file2['data2_train']
print(data2)
type(data2)
data2.shape

[[3688 4381 4594 ... 1064 1034 1010]
 [2579 4137 4412 ... 1051 1043 1005]
 [2581 4264 4328 ... 1054 1022 1009]
 ...
 [3186 4114 4213 ... 1045 1015 1009]
 [2586 4114 4226 ... 1023 1018 1014]
 [3189 4118 4492 ... 1034 1014 1009]]


(1071, 200)

In [39]:
datafile = 'data3_train.mat'
file3 = sio.loadmat(datafile)
data3 = file3['data3_train']
print(data3)
data3.shape

[[3164 4384 4427 ... 1054 1025 1024]
 [3674 4257 4600 ... 1055 1029 1011]
 [2732 4137 4507 ... 1055 1030 1015]
 ...
 [3322 3990 4560 ... 1046 1015 1013]
 [2727 4110 4378 ... 1041 1019 1018]
 [3666 3994 4294 ... 1049 1010 1014]]


(622, 200)

In [40]:
datafile = 'data5_train.mat'
file5 = sio.loadmat(datafile)
data5 = file5['data5_train']
print(data5)
data5.shape

[[3183 3740 3851 ... 1006 1008 1000]
 [2585 3743 4105 ... 1015 1009 1003]
 [2583 3860 3847 ... 1007 1009 1000]
 ...
 [2986 3726 4013 ... 1022 1014 1004]
 [3322 3850 3924 ... 1017 1009 1004]
 [2981 3850 3936 ... 1012 1005 1004]]


(362, 200)

In [41]:
datafile = 'data6_train.mat'
file6 = sio.loadmat(datafile)
data6 = file6['data6_train']
print(data6)
data5.shape

[[3024 3861 3942 ... 1002 1009 1013]
 [3032 3869 4022 ... 1015 1009 1000]
 [2771 4105 3857 ... 1025 1009 1000]
 ...
 [3669 3979 4020 ... 1025 1014 1004]
 [2565 4095 4113 ... 1013  992 1000]
 [3669 3851 4193 ... 1012 1003  995]]


(362, 200)

In [42]:
datafile = 'data8_train.mat'
file8 = sio.loadmat(datafile)
data8 = file8['data8_train']
print(data8)
data8.shape

[[2754 4368 4419 ... 1026 1010 1004]
 [2754 3996 4419 ... 1030 1023 1013]
 [2754 4008 4411 ... 1022 1024 1005]
 ...
 [3192 4235 4313 ... 1026 1023 1000]
 [3192 4111 4313 ... 1030 1014 1008]
 [3192 4115 4313 ... 1031 1014 1013]]


(358, 200)

In [43]:
datafile = 'data10_train.mat'
file10 = sio.loadmat(datafile)
data10 = file10['data10_train']
print(data10)
data10.shape

[[3693 4256 4503 ... 1050 1024 1024]
 [2589 4372 4334 ... 1050 1024 1019]
 [3693 4128 4507 ... 1045 1029 1019]
 ...
 [2564 4238 4290 ... 1042 1023 1018]
 [2735 4114 4295 ... 1041 1024 1018]
 [2732 4122 4388 ... 1054 1024 1014]]


(729, 200)

In [44]:
datafile = 'data11_train.mat'
file11 = sio.loadmat(datafile)
data11 = file11['data11_train']
print(data11)
data11.shape

[[3711 4242 4408 ... 1064 1019 1023]
 [3711 4245 4417 ... 1042 1023 1019]
 [3711 4362 4594 ... 1044 1024 1009]
 ...
 [2728 4350 4473 ... 1040 1018 1005]
 [3154 4106 4299 ... 1040 1018 1023]
 [3154 4226 4384 ... 1045 1023 1001]]


(1841, 200)

In [45]:
datafile = 'data12_train.mat'
file12 = sio.loadmat(datafile)
data12 = file12['data12_train']
print(data12)
data12.shape

[[2564 4131 4333 ... 1041 1016 1010]
 [2737 4019 4418 ... 1041 1020 1019]
 [3663 4383 4321 ... 1045 1025 1015]
 ...
 [3703 4493 4599 ... 1064 1043 1009]
 [3198 4362 4683 ... 1073 1030 1018]
 [3708 4242 4594 ... 1061 1020 1023]]


(445, 200)

In [46]:
datafile = 'data14_train.mat'
file14 = sio.loadmat(datafile)
data14 = file14['data14_train']
print(data14)
data14.shape

[[2574 3874 4134 ... 1014 1010 1003]
 [3174 3881 4045 ... 1021 1010 1009]
 [2577 4121 4054 ... 1012 1006 1004]
 ...
 [2725 3982 4099 ... 1007 1004 1008]
 [3320 3862 4015 ... 1007 1004 1000]
 [3154 3986 4099 ... 1011  996 1003]]


(949, 200)

In [47]:
datafile = 'data_test_final'
test_file = sio.loadmat(datafile)
test_data = test_file['data_test_final']
print(test_data)
test_data.shape

[[3158 4122 4145 ... 1022 1019 1010]
 [3023 3737 4027 ... 1019 1008 1004]
 [2743 4388 4591 ... 1056 1030 1025]
 ...
 [2561 3881 4051 ... 1018  998 1015]
 [2745 4391 4335 ... 1046 1029 1019]
 [3009 3986 3967 ... 1011 1009 1000]]


(2310, 200)

获得数据集

In [48]:
numbers = [1071, 622, 362, 362, 358, 729, 1841, 445, 949]
labels = [2, 3, 5, 6, 8, 10, 11, 12, 14]
data_i = [data2, data3, data5, data6, data8, data10, data11, data12, data14]

In [49]:
all_number = 1071 + 622 + 362 + 362 + 358 + 729 + 1841 + 445 + 949
print(all_number)

6739


In [50]:
data = []
data_y = []
for i in range(9):
    for j in range(numbers[i]):
        data.append(data_i[i][j])

for i in range(9):
    for j in range(numbers[i]):
        data_y.append(labels[i])

In [51]:
data = np.array(data)
data_y = np.array(data_y)

In [52]:
data.shape
print(data)

[[3688 4381 4594 ... 1064 1034 1010]
 [2579 4137 4412 ... 1051 1043 1005]
 [2581 4264 4328 ... 1054 1022 1009]
 ...
 [2725 3982 4099 ... 1007 1004 1008]
 [3320 3862 4015 ... 1007 1004 1000]
 [3154 3986 4099 ... 1011  996 1003]]


划分数据集和训练集（3：7）

In [53]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(data, data_y, test_size = 0.3, random_state = 3)

训练模型

In [54]:
from sklearn import svm
svc = svm.SVC(C = 1, gamma = 1)
svc.fit(x_train, y_train)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [55]:
score = svc.score(x_train, y_train)
print(score)

1.0


使用网格搜索法调参，优化模型

In [56]:
from sklearn.svm import SVC

In [57]:
best_score = 0
for gamma in [0.001,0.01,0.1,1,10,100]:
    for C in [0.001,0.01,0.1,1,10,100]:
        svc = svm.SVC(kernel = 'linear', C = C, gamma = gamma)
        #对于每种参数可能的组合，进行一次训练；
        svc.fit(x_train,y_train)
        score = svc.score(x_test,y_test)
        if score > best_score:
            #找到表现最好的参数
            best_score = score
            best_parameters = {'gamma':gamma,'C':C}

print("Best score:{:.2f}".format(best_score))
print("Best parameters:{}".format(best_parameters))

Best score:0.88
Best parameters:{'gamma': 0.001, 'C': 0.001}


对测试集进行预测

In [58]:
result = svc.predict(test_data)
result = np.array(result)
data_result = pd.DataFrame(result)
data_result.to_csv('result.csv')